#!/bin/bash
# Save context message and restart bot

MESSAGE="$1"

if [ -z "$MESSAGE" ]; then
  echo "Usage: ./save-and-restart.sh \"context message\""
  exit 1
fi

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
SAVE_FILE="docs/tasks/save/restart-context-${TIMESTAMP}.md"

mkdir -p docs/tasks/save

cat > "$SAVE_FILE" <<EOF
# Restart Context - $(date '+%Y-%m-%d %H:%M:%S %Z')

## Message from Previous Session

$MESSAGE

---
*Auto-generated by save-and-restart.sh*
EOF

echo "✅ Context saved to $SAVE_FILE"
echo "🔄 Running make up..."

make up
