import {
  mkdirSync,
  writeFileSync,
  existsSync,
  readdirSync,
  statSync,
  readFileSync,
} from "fs";

export interface ContextStats {
  totalSessions: number;
  totalQueries: number;
  contextPercentage: string;
  contextTokens: number;
  contextWindowSize: number;
}

export interface RestartContextFile {
  name: string;
  path: string;
  mtime: number;
  content: string;
}

export function saveRestartContext(
  saveDir: string,
  stats: ContextStats,
  timestamp?: string
): string {
  mkdirSync(saveDir, { recursive: true });

  const ts = timestamp || new Date().toISOString().replace(/[:.]/g, "-").slice(0, -5);
  const saveFile = `${saveDir}/restart-context-${ts}.md`;
  const now = new Date().toLocaleString("ko-KR", { timeZone: "Asia/Seoul" });

  const content = [
    `# Restart Context - ${now}`,
    ``,
    `## Message from Previous Session`,
    ``,
    `Gracefully shut down via make up. Sessions will be restored automatically.`,
    ``,
    `Active sessions: ${stats.totalSessions}`,
    `Context: ${stats.contextPercentage}% (${stats.contextTokens.toLocaleString()}/${stats.contextWindowSize.toLocaleString()} tokens)`,
    `Total queries: ${stats.totalQueries}`,
    ``,
    `---`,
    `*Auto-generated by SIGTERM handler*`,
  ].join("\n");

  writeFileSync(saveFile, content, "utf-8");
  return saveFile;
}

export function findLatestRestartContext(saveDir: string): RestartContextFile | null {
  if (!existsSync(saveDir)) {
    return null;
  }

  const files = readdirSync(saveDir)
    .filter((f) => f.startsWith("restart-context-") && f.endsWith(".md"))
    .map((f) => ({
      name: f,
      path: `${saveDir}/${f}`,
      mtime: statSync(`${saveDir}/${f}`).mtimeMs,
    }))
    .sort((a, b) => b.mtime - a.mtime);

  if (files.length === 0) {
    return null;
  }

  const latestFile = files[0]!;
  const content = readFileSync(latestFile.path, "utf-8");

  return {
    ...latestFile,
    content,
  };
}

export function formatRestartContextMessage(file: RestartContextFile): string {
  return `\n\n📋 **Saved Context Found:**\n${file.name}\n\n${file.content}`;
}
